<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('empleado', function (Blueprint $table) {
            $table->increments('IDempleado');
            $table->string('foto')->nullable();
            $table->string('nombre', 40);
            $table->string('apellido', 40);
            $table->string('email', 40);
            $table->string('folio', 30);
            $table->date('alta');
            $table->date('termino');
            $table->string('status', 9);
            $table->time('turnoEntrada');
            $table->time('turnoSalida'); 
            $table->string('puesto', 11);
            $table->unsignedInteger('IDdepartamento');
            $table->unsignedInteger('IDasistencia')->nullable();
            $table->unsignedBigInteger('id')->nullable();
            $table->timestamps();

            $table->foreign('IDdepartamento')->references('IDdepartamento')->on('departamento');
            $table->foreign('IDasistencia')->references('IDasistencia')->on('asistencias');
            $table->foreign('id')->references('id')->on('users');
            
        });
        /* 
        DB::table('empleado')->insert([
            [
                'foto' => 'fotos/yBXEImisogT1tHpiCobyZg69CAZrHf6omwPVQgL0.jpg',
                'nombre' => 'Saúl Uriel',
                'apellido' => 'Campos Morales',
                'email' => 'uriel.campos@consultancysc.com',
                'folio' => 'SC2120210802',
                'alta' => '2021-08-02',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '08:00:00',
                'turnoSalida' => '18:00:00',
                'puesto' => 'Jefe',
                'IDdepartamento' => 2,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/vEZAUk5bl2FMh3FKAjpoxhJzrtRJ7jpH0t92k2Q5.png',
                'nombre' => 'Lourdes Ivette',
                'apellido' => 'Campos Morales',
                'email' => 'ivette.campos@consultancysc.com',
                'folio' => 'LC1220210602',
                'alta' => '2021-06-02',
                'termino' => '2024-01-19',
                'status' => 'Activo',
                'turnoEntrada' => '08:00:00',
                'turnoSalida' => '18:00:00',
                'puesto' => 'Jefe',
                'IDdepartamento' => 2,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/EJgqr1wDDZeOicUuaPDy81EmyDn1qX3NgFPoYvH4.jpg',
                'nombre' => 'Miguel Neftali',
                'apellido' => 'Campos Morales',
                'email' => 'miguel.campos@consultancysc.com',
                'folio' => 'MC1820230628',
                'alta' => '2023-06-28',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '08:00:00',
                'turnoSalida' => '18:00:00',
                'puesto' => 'Jefe',
                'IDdepartamento' => 2,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/XqlXTyrtDcfUveyfNVCTGYfQquW2zdPmijxDQ1p2.jpg',
                'nombre' => 'Jimena',
                'apellido' => 'Dorantes Rodriguez',
                'email' => 'jimena.dorantes@consultancysc.com',
                'folio' => 'JD1320230717',
                'alta' => '2023-07-17',
                'termino' => '2024-01-22',
                'status' => 'Activo',
                'turnoEntrada' => '08:00:00',
                'turnoSalida' => '13:00:00',
                'puesto' => 'Psicología',
                'IDdepartamento' => 4,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/xnDJXi7ulfvcUkHNtHS1Jjenu6ZiL7zKlil8LXvj.jpg',
                'nombre' => 'Karen Alejandra',
                'apellido' => 'Palomares Saavedra',
                'email' => 'karen.palomares@consultancysc.com',
                'folio' => 'KP2720230904',
                'alta' => '2023-09-04',
                'termino' => '2024-01-23',
                'status' => 'Activo',
                'turnoEntrada' => '08:00:00',
                'turnoSalida' => '16:00:00',
                'puesto' => 'Jefe',
                'IDdepartamento' => 4,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/BFdi1ZRmP5HWTSEGN0c8oAMPKdMzRBnW67icUhuV.jpg',
                'nombre' => 'Ivana',
                'apellido' => 'Serrato Ulloa',
                'email' => 'ivana.serrato@consultancysc.com',
                'folio' => 'IS4520230928',
                'alta' => '2023-09-28',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '13:00:00',
                'turnoSalida' => '18:00:00',
                'puesto' => 'Practicante',
                'IDdepartamento' => 4,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/3Y9uplZvapcHjSW4KekrABhEr19VpJnNlRJssGTl.jpg',
                'nombre' => 'Daira Shaiel',
                'apellido' => 'Muñoz Alvarado',
                'email' => 'daira.munoz@consultancysc.com',
                'folio' => 'DM4920231017',
                'alta' => '2023-10-17',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '08:00:00',
                'turnoSalida' => '13:00:00',
                'puesto' => 'Practicante',
                'IDdepartamento' => 4,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/G84hDs8rkoSwHCbKV3p8qpwPBkv24wR41VwoEgjo.png',
                'nombre' => 'Marlene Fiorella',
                'apellido' => 'Marlene Fiorella',
                'email' => 'marlene.moran@consultancysc.com',
                'folio' => 'MM012023125',
                'alta' => '2023-12-01',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '13:00:00',
                'turnoSalida' => '18:00:00',
                'puesto' => 'Practicante',
                'IDdepartamento' => 4,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/gBiJPaLARTraeh0a8mGimdHq5HVc73uwggZwP6xI.jpg',
                'nombre' => 'Adriana Isela',
                'apellido' => 'Vargas Flores',
                'email' => 'adriana.vargas@consultancysc.com',
                'folio' => 'AV032024016',
                'alta' => '2024-01-03',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '08:00:00',
                'turnoSalida' => '13:00:00',
                'puesto' => 'Practicante',
                'IDdepartamento' => 5,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/tumyp7qbJwlI60d695Im2LXkJvOESSzYVOF9fJoW.jpg',
                'nombre' => 'Brenda Annel',
                'apellido' => 'Flores Jacobo',
                'email' => 'brenda.flores@consultancysc.com',
                'folio' => 'BF092024016',
                'alta' => '2024-01-09',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '09:00:00',
                'turnoSalida' => '14:00:00',
                'puesto' => 'Practicante',
                'IDdepartamento' => 5,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/biAfOp321Lwo5XNkDNfvNvImu5jtfB2OW6PKcSYz.jpg',
                'nombre' => 'Oscar Antonio',
                'apellido' => 'Durán Ojeda',
                'email' => 'oscar.duran@consultancysc.com',
                'folio' => 'OD092024016',
                'alta' => '2024-01-09',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '13:00:00',
                'turnoSalida' => '18:00:00',
                'puesto' => 'Practicante',
                'IDdepartamento' => 5,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/zCSYDL1YaSZWKCr0LvEmyJIKKeYMja9QC4YA65XH.jpg',
                'nombre' => 'Karla Yahel',
                'apellido' => 'Martínez Calderón',
                'email' => 'karla.martinez@consultancysc.com',
                'folio' => 'KM1620220725',
                'alta' => '2022-07-25',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '15:00:00',
                'turnoSalida' => '16:00:00',
                'puesto' => 'Jefe',
                'IDdepartamento' => 6,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/wOEIxtiG1AqFQxz20846WxHhOBY5WvYgCASeNruZ.jpg',
                'nombre' => 'Rubén',
                'apellido' => 'Grimaldo García',
                'email' => 'ruben.garcia@consultancysc.com',
                'folio' => 'RG042024017',
                'alta' => '2024-01-04',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '08:00:00',
                'turnoSalida' => '13:00:00',
                'puesto' => 'Practicante',
                'IDdepartamento' => 6,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/8nYsKKWheO9tt23mb6ibburEMbwhFSvfTG4dmySd.jpg',
                'nombre' => 'María Magdalena',
                'apellido' => 'Hernández García',
                'email' => 'maria.hernandez@consultancysc.com',
                'folio' => 'MH3620230912',
                'alta' => '2023-09-12',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '08:00:00',
                'turnoSalida' => '18:00:00',
                'puesto' => 'Jefe',
                'IDdepartamento' => 9,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/hQkVmAFavHhfORSqLqSQue4zh9oXBsYgBUO6Im0Q.jpg',
                'nombre' => 'Daniela Nohemi',
                'apellido' => 'Osorio Contreras',
                'email' => 'daniela.osorio@consultancysc.com',
                'folio' => 'DO4620231003',
                'alta' => '2023-10-03',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '09:00:00',
                'turnoSalida' => '14:00:00',
                'puesto' => 'Jefe',
                'IDdepartamento' => 9,
                'IDasistencia' => null,
                'id' => null,
            ],

            [
                'foto' => 'fotos/NGc8yE81PdsS3zMrW3JmyVK27Szyd1j54vmHHknR.jpg',
                'nombre' => 'José Manuel',
                'apellido' => 'Heras Gómez',
                'email' => 'jose.heras@consultancysc.com',
                'folio' => 'JH5420231123',
                'alta' => '2023-11-23',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '08:00:00',
                'turnoSalida' => '13:00:00',
                'puesto' => 'Practicante',
                'IDdepartamento' => 9,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/NUWz4ZYJF5gHlvVHIaPa0LTs6iXGX56Wtx7GpfrH.jpg',
                'nombre' => 'Oscar Alexis',
                'apellido' => 'Aguilar Sánchez',
                'email' => 'oscar.aguilar@consultancysc.com',
                'folio' => 'OA1920230116',
                'alta' => '2023-01-16',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '09:00:00',
                'turnoSalida' => '14:00:00',
                'puesto' => 'Jefe',
                'IDdepartamento' => 7,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/jt8c3NnupOR2Mse3vEHzy0enFnD9QMpF5aDIlMQh.png',
                'nombre' => 'Adolfo Alexis',
                'apellido' => 'Mendoza Pacheco',
                'email' => 'adolfo.mendoza@consultancysc.com',
                'folio' => 'AM0120230801',
                'alta' => '2023-08-01',
                'termino' => '2024-03-22',
                'status' => 'Activo',
                'turnoEntrada' => '13:00:00',
                'turnoSalida' => '17:00:00',
                'puesto' => 'Jefe',
                'IDdepartamento' => 7,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/YOPgCVDYlgMHExm87WRa2Bc30MJzeHJRk7jlem7s.jpg',
                'nombre' => 'Joseph',
                'apellido' => 'Ríos Hernández',
                'email' => 'joseph.hernandez@consultancysc.com',
                'folio' => 'JR032024018',
                'alta' => '2024-01-03',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '08:00:00',
                'turnoSalida' => '15:00:00',
                'puesto' => 'Practicante',
                'IDdepartamento' => 7,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/hfx8oOUkBy0Lc7zPlhakI7Rwr7IOWgVo9ROM5zcd.jpg',
                'nombre' => 'Azucena del Rocío',
                'apellido' => 'Escobar Márquez',
                'email' => 'azucena.escobar@consultancysc.com',
                'folio' => 'AE5120231023',
                'alta' => '2023-10-23',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '08:00:00',
                'turnoSalida' => '13:00:00',
                'puesto' => 'Jefe',
                'IDdepartamento' => 8,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/WajcFtoYSfviaRpzxbTpDN0ka8sBXRWb01V8lXmg.jpg',
                'nombre' => 'Montserrat',
                'apellido' => 'Landín Arredondo',
                'email' => 'montserrat.landin@consultancysc.com',
                'folio' => 'ML4820231009',
                'alta' => '2023-10-09',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '08:00:00',
                'turnoSalida' => '16:00:00',
                'puesto' => 'Jefe',
                'IDdepartamento' => 8,
                'IDasistencia' => null,
                'id' => null,
            ],
            [
                'foto' => 'fotos/dU0aUyWJbd5rtpFslFXt6vvgDYf2JYj6HiDoxDA3.jpg',
                'nombre' => 'Natalia Estefania',
                'apellido' => 'Cortes Salazar',
                'email' => 'natalia.cortes@consultancysc.com',
                'folio' => 'NC2520230828',
                'alta' => '2023-08-28',
                'termino' => '2024-01-11',
                'status' => 'Activo',
                'turnoEntrada' => '11:00:00',
                'turnoSalida' => '15:00:00',
                'puesto' => 'Practicante',
                'IDdepartamento' => 10,
                'IDasistencia' => null,
                'id' => null,
            ],
            
        ]);

       */
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('empleado');
    }
};